### ISSUE TITLE
License Review

### ISSUE THREAD

**Issue by wzip** [New-Jersey-Forest-Service/ForMOM-Builder#1]
Looking though this source; It tentatively looks ok to go public with an MIT License; Working on final review.

**Comment by MrGorbunov** [comment]
Here are the dependencies:

**attrs==21.4.0**  :heavy_check_mark: 
MIT License: https://www.attrs.org/en/stable/license.html

**cattrs==22.1.0** :heavy_check_mark: 
MIT License: https://github.com/python-attrs/cattrs

**exceptiongroup==1.0.0rc8** :heavy_check_mark: 
MIT and PSF License: https://github.com/agronholm/exceptiongroup/blob/main/LICENSE

Note that PSF is the license standard library python uses, and exception group is a backport of python 3.11 features, so I think the original code is PSF while the back port is MIT. Either way it's not an issue.

**Comment by wzip** [comment]
This repo is consistent with its license and ready to be made public.

**Comment by MrGorbunov** [comment]
Repo has been made public :+1:
